name:                surf
version:             1.0.0.0
github:              "magnunm/surf"
license:             BSD3
author:              "Magnus Nybråten Malmquist"
copyright:           "2023 Magnus Nybråten Malmquist"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- http-client >= 0.6.4.1
- req >= 3.9.0
- text >= 1.2.4
- bytestring >= 0.10.12.0
- case-insensitive >= 1.2.1.0
- rainbow >= 0.34.2.2

default-extensions:
- DataKinds
- TupleSections
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  surf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - surf
